// components/layout/app-shell.tsx
import type { ReactNode } from "react";

import { MobileNav } from "@/components/layout/mobile-nav";
import { SideNav } from "@/components/layout/side-nav";
import { type ShellActor, TopNav } from "@/components/layout/top-nav";

export function AppShell({ children, actor }: { children: ReactNode; actor: ShellActor }) {
  return (
    <div className="min-h-dvh bg-slate-50 text-slate-950">
      <div className="mx-auto flex min-h-dvh max-w-7xl gap-6 px-2 pb-[calc(4rem+env(safe-area-inset-bottom))] pt-[max(0.75rem,env(safe-area-inset-top))] min-[360px]:px-4 md:px-6 md:py-6">
        <SideNav role={actor.role} />
        <div className="flex min-h-full min-w-0 flex-1 flex-col gap-6"><TopNav actor={actor} /><main className="flex-1 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm min-[360px]:p-4 md:p-6">{children}</main></div>
      </div>
      <MobileNav role={actor.role} />
    </div>
  );
}

// app/components/layout/AppShell.vue
<script setup lang="ts">
const { actor } = useAuth();
</script>

<template>
  <ElContainer class="app-shell">
    <SideNav :role="actor?.role" />
    <ElContainer class="content-column">
      <TopNav />
      <ElMain class="app-main">
        <slot />
      </ElMain>
    </ElContainer>
    <MobileNav :role="actor?.role" />
  </ElContainer>
</template>

<style scoped>
.app-shell { width: min(100%, 1280px); min-height: 100dvh; margin: 0 auto; gap: 24px; padding: 24px; }
.content-column { min-width: 0; flex-direction: column; }
.app-main { flex: 1; padding: 24px; overflow: visible; border: 1px solid #e2e8f0; border-radius: 16px; background: white; box-shadow: 0 1px 3px rgb(15 23 42 / 8%); }
@media (max-width: 767px) {
  .app-shell { display: block; padding: max(12px, env(safe-area-inset-top)) 12px calc(76px + env(safe-area-inset-bottom)); }
  .app-main { padding: 16px; }
}
</style>
