// app/components/medicines/MedicineDashboard.vue
<script setup lang="ts">
import type { Medicine, MedicineAttachmentType, MedicineStatus } from "./medicine";
import { attachmentSections, categories, dateInput, formatDate, statusLabel, units } from "./medicine";

const props = defineProps<{ initialItems: Medicine[] }>();
const { apiFetch } = useApi();
const items = ref([...props.initialItems]);
const search = ref(""); const category = ref("all"); const status = ref<"all" | MedicineStatus>("all"); const tag = ref("");
const dialog = ref(false); const saving = ref(false); const editingId = ref<string | null>(null);
const blank = () => ({ name: "", category: "其他", tags: "", quantityTotal: null as number | null, quantityRemaining: null as number | null, unit: "盒", lowStockThreshold: null as number | null, locationText: "", contentText: "", openedAt: "", expiresAt: "", expirationReminderDays: 30, notes: "" });
const form = reactive(blank());
const pending = reactive<Record<MedicineAttachmentType, File[]>>({ medicine_photo: [], medicine_location: [], medicine_content: [] });
const stats = computed(() => ({ total: items.value.length, opened: items.value.filter(i => i.openedAt).length, expiring: items.value.filter(i => i.status === "expiring_soon").length, expired: items.value.filter(i => i.status === "expired").length, low: items.value.filter(i => ["low_stock", "empty"].includes(i.status)).length }));
const filtered = computed(() => items.value.filter(item => {
  const word = search.value.trim().toLowerCase(); const tagWord = tag.value.trim().toLowerCase();
  const haystack = [item.name, item.category, item.tags, item.locationText, item.contentText].filter(Boolean).join(" ").toLowerCase();
  return (!word || haystack.includes(word)) && (category.value === "all" || item.category === category.value) && (status.value === "all" || item.status === status.value) && (!tagWord || (item.tags || "").toLowerCase().includes(tagWord));
}));
function clearPending() { for (const section of attachmentSections) pending[section.type] = []; }
function openCreate() { editingId.value = null; Object.assign(form, blank()); clearPending(); dialog.value = true; }
function openEdit(item: Medicine) { editingId.value = item.id; Object.assign(form, { ...item, tags: item.tags || "", locationText: item.locationText || "", contentText: item.contentText || "", notes: item.notes || "", openedAt: dateInput(item.openedAt), expiresAt: dateInput(item.expiresAt) }); clearPending(); dialog.value = true; }
function addFile(type: MedicineAttachmentType, file: File) { if (!file.type.startsWith("image/")) return ElMessage.error("请上传图片附件"); if (file.size > 20 * 1024 * 1024) return ElMessage.error("药品图片不能超过 20MB"); pending[type].push(file); }
async function save() {
  if (!form.name.trim()) return ElMessage.warning("请输入药品名称");
  saving.value = true;
  try {
    const path = editingId.value ? `/api/medicines/${editingId.value}` : "/api/medicines";
    const result = await apiFetch<{ item: Medicine }>(path, { method: editingId.value ? "PUT" : "POST", body: { ...form, openedAt: form.openedAt || null, expiresAt: form.expiresAt || null } });
    const index = items.value.findIndex(i => i.id === result.item.id); if (index < 0) items.value.unshift(result.item); else items.value[index] = result.item;
    let count = 0;
    for (const section of attachmentSections) for (const file of pending[section.type]) { const body = new FormData(); body.append("file", file); body.append("attachmentType", section.type); await apiFetch(`/api/medicines/${result.item.id}/attachments`, { method: "POST", body }); count++; }
    dialog.value = false; clearPending(); ElMessage.success(count ? `药品已保存，并上传了 ${count} 张附件` : "药品已保存，过期提醒已同步");
  } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); } finally { saving.value = false; }
}
async function remove(item: Medicine) {
  try { await ElMessageBox.confirm(`确定归档药品「${item.name}」吗？`, "归档药品", { type: "warning" }); await apiFetch(`/api/medicines/${item.id}`, { method: "DELETE" }); items.value = items.value.filter(i => i.id !== item.id); ElMessage.success("药品已归档，关联提醒已同步"); }
  catch (error) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "归档失败"); }
}
</script>
<template>
  <div class="page">
    <header><div><small>家庭药箱</small><h1>药品管理</h1><p>管理剩余量、位置、附件和过期提醒。</p></div><ElButton type="primary" @click="openCreate">新增药品</ElButton></header>
    <div class="stats"><ElCard v-for="(value,key) in stats" :key="key" shadow="never"><small>{{ {total:'总数',opened:'已开封',expiring:'即将过期',expired:'已过期',low:'库存不足'}[key] }}</small><strong>{{ value }}</strong></ElCard></div>
    <ElCard shadow="never"><div class="filters"><ElInput v-model="search" clearable placeholder="搜索药名/位置/内容"/><ElSelect v-model="category"><ElOption label="全部分类" value="all"/><ElOption v-for="entry in categories" :key="entry" :label="entry" :value="entry"/></ElSelect><ElSelect v-model="status"><ElOption label="全部状态" value="all"/><ElOption v-for="(label,value) in statusLabel" :key="value" :label="label" :value="value"/></ElSelect><ElInput v-model="tag" clearable placeholder="标签筛选"/></div></ElCard>
    <ElEmpty v-if="!filtered.length" description="没有符合条件的药品"/>
    <div class="cards"><ElCard v-for="item in filtered" :key="item.id" shadow="hover"><template #header><div class="card-head"><div><h2>{{ item.name }}</h2><small>{{ item.category }}{{ item.tags ? ` · ${item.tags}` : '' }}</small></div><ElTag>{{ statusLabel[item.status] }}</ElTag></div></template><div class="details"><span>剩余量<br><b>{{ item.quantityRemaining ?? '-' }}{{ item.unit }}</b></span><span>过期日期<br><b>{{ formatDate(item.expiresAt) }}</b></span><span>位置<br><b>{{ item.locationText || '未填写' }}</b></span></div><p v-if="item.contentText">{{ item.contentText }}</p><div class="actions"><NuxtLink :to="`/medicines/${item.id}`"><ElButton type="primary">查看明细</ElButton></NuxtLink><ElButton @click="openEdit(item)">编辑</ElButton><ElButton type="danger" plain @click="remove(item)">归档</ElButton></div></ElCard></div>
    <ElDialog v-model="dialog" :title="editingId ? '编辑药品' : '新增药品'" width="min(900px, 94vw)" destroy-on-close>
      <ElForm label-position="top" @submit.prevent="save"><div class="form-grid"><ElFormItem label="药品名称" required><ElInput v-model="form.name"/></ElFormItem><ElFormItem label="分类"><ElSelect v-model="form.category"><ElOption v-for="entry in categories" :key="entry" :label="entry" :value="entry"/></ElSelect></ElFormItem><ElFormItem label="标签"><ElInput v-model="form.tags" placeholder="退烧,止痛"/></ElFormItem><ElFormItem label="总数量"><ElInputNumber v-model="form.quantityTotal" :min="0"/></ElFormItem><ElFormItem label="剩余量"><ElInputNumber v-model="form.quantityRemaining" :min="0"/></ElFormItem><ElFormItem label="单位"><ElSelect v-model="form.unit"><ElOption v-for="entry in units" :key="entry" :label="entry" :value="entry"/></ElSelect></ElFormItem><ElFormItem label="低库存阈值"><ElInputNumber v-model="form.lowStockThreshold" :min="0"/></ElFormItem><ElFormItem label="开封时间"><ElDatePicker v-model="form.openedAt" type="date" value-format="YYYY-MM-DD"/></ElFormItem><ElFormItem label="过期日期"><ElDatePicker v-model="form.expiresAt" type="date" value-format="YYYY-MM-DD"/></ElFormItem><ElFormItem label="提前提醒天数"><ElInputNumber v-model="form.expirationReminderDays" :min="0" :max="3650"/></ElFormItem><ElFormItem label="存放位置"><ElInput v-model="form.locationText"/></ElFormItem><ElFormItem label="备注"><ElInput v-model="form.notes"/></ElFormItem></div><ElFormItem label="药品内容（文字）"><ElInput v-model="form.contentText" type="textarea" :rows="4"/></ElFormItem>
      <div class="attachments"><div v-for="section in attachmentSections" :key="section.type"><b>{{ section.title }}</b><small>{{ section.description }}</small><FileUpload accept="image/*" multiple :limit-bytes="20*1024*1024" :disabled="saving" @select="addFile(section.type,$event)" @error="ElMessage.error($event)"/><ElTag v-for="(file,index) in pending[section.type]" :key="`${file.name}-${index}`" closable @close="pending[section.type].splice(index,1)">{{ file.name }}</ElTag></div></div>
      </ElForm><template #footer><ElButton @click="dialog=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="save">保存</ElButton></template>
    </ElDialog>
  </div>
</template>
<style scoped>.page{display:grid;gap:20px}header,.card-head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}h1,h2,p{margin:0}header p,header small,.card-head small{color:#64748b}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.stats :deep(.el-card__body){display:grid;gap:6px}.stats strong{font-size:24px}.filters,.form-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.details{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;color:#64748b;margin-bottom:14px}.details b{color:#334155}.actions{justify-content:flex-start;margin-top:16px}.attachments{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.attachments>div{display:grid;gap:8px;border:1px solid #e2e8f0;padding:12px;border-radius:10px}.attachments small{color:#64748b}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.filters,.form-grid,.cards,.attachments{grid-template-columns:1fr}header{align-items:flex-start}}</style>

// components/medicines/medicine-dashboard.tsx
"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { MEDICINE_CATEGORIES, MEDICINE_UNITS, getMedicineStatusLabel, type MedicineStatus } from "@/lib/medicines";

type MedicineItem = {
  id: string;
  name: string;
  category: string;
  tags: string | null;
  quantityTotal: number | null;
  quantityRemaining: number | null;
  unit: string;
  lowStockThreshold: number | null;
  locationText: string | null;
  contentText: string | null;
  openedAt: string | null;
  expiresAt: string | null;
  expirationReminderDays: number;
  notes: string | null;
  status: MedicineStatus;
};

type MedicineFormState = {
  name: string;
  category: string;
  tags: string;
  quantityTotal: string;
  quantityRemaining: string;
  unit: string;
  lowStockThreshold: string;
  locationText: string;
  contentText: string;
  openedAt: string;
  expiresAt: string;
  expirationReminderDays: string;
  notes: string;
};

const emptyForm: MedicineFormState = {
  name: "",
  category: "其他",
  tags: "",
  quantityTotal: "",
  quantityRemaining: "",
  unit: "盒",
  lowStockThreshold: "",
  locationText: "",
  contentText: "",
  openedAt: "",
  expiresAt: "",
  expirationReminderDays: "30",
  notes: "",
};

const statusOptions: Array<{ value: "all" | MedicineStatus; label: string }> = [
  { value: "all", label: "全部状态" },
  { value: "normal", label: "正常" },
  { value: "expiring_soon", label: "即将过期" },
  { value: "expired", label: "已过期" },
  { value: "low_stock", label: "库存偏低" },
  { value: "empty", label: "已用完" },
];

function toDateInput(value: string | null) {
  return value ? new Date(value).toISOString().slice(0, 10) : "";
}

function formFromMedicine(item: MedicineItem): MedicineFormState {
  return {
    name: item.name,
    category: item.category,
    tags: item.tags ?? "",
    quantityTotal: item.quantityTotal?.toString() ?? "",
    quantityRemaining: item.quantityRemaining?.toString() ?? "",
    unit: item.unit,
    lowStockThreshold: item.lowStockThreshold?.toString() ?? "",
    locationText: item.locationText ?? "",
    contentText: item.contentText ?? "",
    openedAt: toDateInput(item.openedAt),
    expiresAt: toDateInput(item.expiresAt),
    expirationReminderDays: item.expirationReminderDays?.toString() ?? "30",
    notes: item.notes ?? "",
  };
}

function toPayload(form: MedicineFormState) {
  return {
    name: form.name,
    category: form.category,
    tags: form.tags,
    quantityTotal: form.quantityTotal === "" ? null : Number(form.quantityTotal),
    quantityRemaining: form.quantityRemaining === "" ? null : Number(form.quantityRemaining),
    unit: form.unit,
    lowStockThreshold: form.lowStockThreshold === "" ? null : Number(form.lowStockThreshold),
    locationText: form.locationText,
    contentText: form.contentText,
    openedAt: form.openedAt || null,
    expiresAt: form.expiresAt || null,
    expirationReminderDays: Number(form.expirationReminderDays || 30),
    notes: form.notes,
  };
}

function statusClass(status: MedicineStatus) {
  return {
    normal: "bg-emerald-50 text-emerald-700",
    expiring_soon: "bg-amber-50 text-amber-700",
    expired: "bg-red-50 text-red-700",
    low_stock: "bg-orange-50 text-orange-700",
    empty: "bg-slate-100 text-slate-600",
  }[status];
}

function formatDate(value: string | null) {
  return value ? new Date(value).toLocaleDateString("zh-CN") : "未填写";
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="space-y-1 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>;
}

export function MedicineDashboard() {
  const [items, setItems] = useState<MedicineItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [editing, setEditing] = useState<MedicineItem | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState<MedicineFormState>(emptyForm);
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [status, setStatus] = useState<"all" | MedicineStatus>("all");
  const [tag, setTag] = useState("");

  const loadItems = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/medicines", { cache: "no-store" });
      const data = (await response.json()) as { items?: MedicineItem[]; error?: string };
      if (!response.ok || !data.items) throw new Error(data.error ?? "加载药品失败");
      setItems(data.items);
      setMessage(null);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "加载药品失败");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void Promise.resolve().then(loadItems);
  }, [loadItems]);

  const filtered = useMemo(() => {
    const keyword = search.trim().toLowerCase();
    const tagKeyword = tag.trim().toLowerCase();
    return items.filter((item) => {
      const haystack = [item.name, item.category, item.tags, item.locationText, item.contentText].filter(Boolean).join(" ").toLowerCase();
      if (keyword && !haystack.includes(keyword)) return false;
      if (category !== "all" && item.category !== category) return false;
      if (status !== "all" && item.status !== status) return false;
      if (tagKeyword && !(item.tags ?? "").toLowerCase().includes(tagKeyword)) return false;
      return true;
    });
  }, [items, search, category, status, tag]);

  const stats = useMemo(() => ({
    total: items.length,
    opened: items.filter((item) => item.openedAt).length,
    expiring: items.filter((item) => item.status === "expiring_soon").length,
    expired: items.filter((item) => item.status === "expired").length,
    low: items.filter((item) => item.status === "low_stock" || item.status === "empty").length,
  }), [items]);

  function openCreate() {
    setEditing(null);
    setForm(emptyForm);
    setFormOpen(true);
    setMessage(null);
  }

  function openEdit(item: MedicineItem) {
    setEditing(item);
    setForm(formFromMedicine(item));
    setFormOpen(true);
    setMessage(null);
  }

  async function saveMedicine(event: React.FormEvent) {
    event.preventDefault();
    setSaving(true);
    try {
      const response = await fetch(editing ? `/api/medicines/${editing.id}` : "/api/medicines", {
        method: editing ? "PUT" : "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(toPayload(form)),
      });
      const data = (await response.json()) as { item?: MedicineItem; error?: string };
      if (!response.ok || !data.item) throw new Error(data.error ?? "保存失败");
      const saved = data.item;
      setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]);
      setFormOpen(false);
      setMessage("药品已保存");
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "保存失败");
    } finally {
      setSaving(false);
    }
  }

  async function deleteMedicine(item: MedicineItem) {
    if (!confirm(`确定归档药品「${item.name}」吗？`)) return;
    const response = await fetch(`/api/medicines/${item.id}`, { method: "DELETE" });
    if (response.ok) setItems((current) => current.filter((entry) => entry.id !== item.id));
  }

  return (
    <div className="flex min-w-0 flex-col gap-5 sm:gap-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-sm text-slate-500">家庭药箱</p>
          <h1 className="text-balance text-2xl font-bold text-slate-950">药品管理</h1>
          <p className="mt-1 text-sm text-slate-500">管理已开封但未用完的家庭人用药品、剩余量、位置、附件和过期提醒。</p>
        </div>
        <Button type="button" onClick={openCreate}>新增药品</Button>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {[['总数', stats.total], ['已开封', stats.opened], ['即将过期', stats.expiring], ['已过期', stats.expired], ['库存不足', stats.low]].map(([label, value]) => (
          <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold text-slate-950">{value}</p></div>
        ))}
      </div>

      {message ? <p className="rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm text-blue-700">{message}</p> : null}

      <div className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-4">
        <input className="min-h-11 rounded-lg border border-slate-200 px-3 text-sm" placeholder="搜索药名/位置/内容" value={search} onChange={(e) => setSearch(e.target.value)} />
        <select className="min-h-11 rounded-lg border border-slate-200 px-3 text-sm" value={category} onChange={(e) => setCategory(e.target.value)}>
          <option value="all">全部分类</option>
          {MEDICINE_CATEGORIES.map((entry) => <option key={entry} value={entry}>{entry}</option>)}
        </select>
        <select className="min-h-11 rounded-lg border border-slate-200 px-3 text-sm" value={status} onChange={(e) => setStatus(e.target.value as "all" | MedicineStatus)}>
          {statusOptions.map((entry) => <option key={entry.value} value={entry.value}>{entry.label}</option>)}
        </select>
        <input className="min-h-11 rounded-lg border border-slate-200 px-3 text-sm" placeholder="标签筛选" value={tag} onChange={(e) => setTag(e.target.value)} />
      </div>

      {formOpen ? (
        <form onSubmit={saveMedicine} className="space-y-4 rounded-xl border border-slate-200 bg-white p-4 sm:p-5">
          <div className="flex items-center justify-between"><h2 className="font-semibold text-slate-950">{editing ? "编辑药品" : "新增药品"}</h2><button type="button" className="text-sm text-slate-500" onClick={() => setFormOpen(false)}>关闭</button></div>
          <div className="grid gap-4 md:grid-cols-3">
            <Field label="药品名称"><input required className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field>
            <Field label="分类"><select className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{MEDICINE_CATEGORIES.map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></Field>
            <Field label="标签"><input className="min-h-11 w-full rounded-lg border border-slate-200 px-3" placeholder="如：退烧,止痛" value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} /></Field>
            <Field label="总数量"><input type="number" min="0" step="0.01" className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.quantityTotal} onChange={(e) => setForm({ ...form, quantityTotal: e.target.value })} /></Field>
            <Field label="剩余量"><input type="number" min="0" step="0.01" className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.quantityRemaining} onChange={(e) => setForm({ ...form, quantityRemaining: e.target.value })} /></Field>
            <Field label="单位"><select className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })}>{MEDICINE_UNITS.map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></Field>
            <Field label="低库存阈值"><input type="number" min="0" step="0.01" className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.lowStockThreshold} onChange={(e) => setForm({ ...form, lowStockThreshold: e.target.value })} /></Field>
            <Field label="开封时间"><input type="date" className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.openedAt} onChange={(e) => setForm({ ...form, openedAt: e.target.value })} /></Field>
            <Field label="过期日期"><input type="date" className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} /></Field>
            <Field label="提前提醒天数"><input type="number" min="0" max="3650" className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.expirationReminderDays} onChange={(e) => setForm({ ...form, expirationReminderDays: e.target.value })} /></Field>
            <Field label="存放位置"><input className="min-h-11 w-full rounded-lg border border-slate-200 px-3" placeholder="如：客厅药箱第二层" value={form.locationText} onChange={(e) => setForm({ ...form, locationText: e.target.value })} /></Field>
            <Field label="备注"><input className="min-h-11 w-full rounded-lg border border-slate-200 px-3" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field>
          </div>
          <Field label="药品内容（文字）"><textarea className="min-h-28 w-full rounded-lg border border-slate-200 p-3" placeholder="用法、注意事项、医嘱等；也可以在详情中上传内容照片" value={form.contentText} onChange={(e) => setForm({ ...form, contentText: e.target.value })} /></Field>
          <div className="flex justify-end gap-2"><Button type="button" className="bg-slate-100 text-slate-700 hover:bg-slate-200" onClick={() => setFormOpen(false)}>取消</Button><Button type="submit" disabled={saving}>{saving ? "保存中..." : "保存"}</Button></div>
        </form>
      ) : null}

      {loading ? <div className="rounded-xl border border-dashed border-slate-200 p-10 text-center text-slate-500">加载药品...</div> : null}
      {!loading && filtered.length === 0 ? <div className="rounded-xl border border-dashed border-slate-200 p-10 text-center text-slate-500">没有符合条件的药品</div> : null}
      <div className="grid gap-4 lg:grid-cols-2">
        {filtered.map((item) => (
          <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0"><h2 className="truncate text-lg font-semibold text-slate-950">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.category}{item.tags ? ` · ${item.tags}` : ""}</p></div>
              <span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${statusClass(item.status)}`}>{getMedicineStatusLabel(item.status)}</span>
            </div>
            <div className="mt-4 grid grid-cols-2 gap-3 text-sm text-slate-600 sm:grid-cols-4">
              <p><span className="block text-xs text-slate-400">剩余量</span>{item.quantityRemaining ?? "-"}{item.unit}</p>
              <p><span className="block text-xs text-slate-400">过期日期</span>{formatDate(item.expiresAt)}</p>
              <p><span className="block text-xs text-slate-400">开封时间</span>{formatDate(item.openedAt)}</p>
              <p><span className="block text-xs text-slate-400">位置</span>{item.locationText || "未填写"}</p>
            </div>
            {item.contentText ? <p className="mt-3 line-clamp-2 text-sm text-slate-500">{item.contentText}</p> : null}
            <div className="mt-4 flex flex-wrap gap-2"><Link className="inline-flex min-h-10 items-center rounded-lg bg-blue-600 px-3 text-sm font-medium text-white" href={`/medicines/${item.id}`}>查看明细</Link><Button type="button" className="bg-slate-100 text-slate-700 hover:bg-slate-200" onClick={() => openEdit(item)}>编辑</Button><Button type="button" className="bg-red-50 text-red-600 hover:bg-red-100" onClick={() => void deleteMedicine(item)}>归档</Button></div>
          </article>
        ))}
      </div>
    </div>
  );
}
