// components/reminders/reminder-form.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FileUpload } from "@/components/ui/file-upload";
import { isActivationReminder } from "@/lib/reminder-kind";
import type { ReminderRecurrenceType } from "@/lib/reminder-recurrence";
import { REMINDER_GROUPS, getReminderGroup, type ReminderGroup } from "@/lib/reminder-groups";

type RecurrenceSelectValue = ReminderRecurrenceType | "none";

type ReminderFormValues = {
  id?: string;
  title?: string;
  description?: string;
  activationCode?: string | null;
  activationContact?: string | null;
  dueAt?: string;
  category?: string;
  priority?: "low" | "medium" | "high";
  remindBeforeDays?: number;
  remindBeforeHours?: number;
  overdueRemindEnabled?: boolean;
  recurrenceType?: ReminderRecurrenceType | null;
  recurrenceInterval?: number | null;
};

type Attachment = {
  id: string;
  originalName: string;
  mimetype: string;
  size: number;
  url: string;
  createdAt: string;
};

type ReminderFormProps = {
  mode: "create" | "edit";
  defaultValues?: ReminderFormValues;
  attachments?: Attachment[];
};

export function ReminderForm({ mode, defaultValues, attachments }: ReminderFormProps) {
  const router = useRouter();
  const [title, setTitle] = useState(defaultValues?.title ?? "");
  const [dueAt, setDueAt] = useState(defaultValues?.dueAt ?? "");
  const [category, setCategory] = useState<ReminderGroup>(defaultValues?.category ? getReminderGroup(defaultValues.category) : "其他");
  const [description, setDescription] = useState(defaultValues?.description ?? "");
  const [reminderKind, setReminderKind] = useState<"normal" | "activation">(
    isActivationReminder(defaultValues?.activationCode) ? "activation" : "normal",
  );
  const [activationCode, setActivationCode] = useState(defaultValues?.activationCode ?? "");
  const [activationContact, setActivationContact] = useState(defaultValues?.activationContact ?? "");
  const [priority, setPriority] = useState<"low" | "medium" | "high">(defaultValues?.priority ?? "medium");
  const [remindBeforeDays, setRemindBeforeDays] = useState(String(defaultValues?.remindBeforeDays ?? 3));
  const [remindBeforeHours, setRemindBeforeHours] = useState(String(defaultValues?.remindBeforeHours ?? 0));
  const [overdueRemindEnabled, setOverdueRemindEnabled] = useState(defaultValues?.overdueRemindEnabled ?? true);
  const [recurrenceType, setRecurrenceType] = useState<RecurrenceSelectValue>(
    defaultValues?.recurrenceType ?? "none",
  );
  const [recurrenceInterval, setRecurrenceInterval] = useState(String(defaultValues?.recurrenceInterval ?? 1));
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!dueAt) {
      setMessage("请先选择截止时间");
      return;
    }

    if (recurrenceType !== "none" && Number(recurrenceInterval) < 1) {
      setMessage("周期数值必须大于等于 1");
      return;
    }

    setSubmitting(true);
    setMessage(null);

    try {
      const endpoint = mode === "create" ? "/api/reminders" : `/api/reminders/${defaultValues?.id ?? ""}`;
      const method = mode === "create" ? "POST" : "PUT";
      const response = await fetch(endpoint, {
        method,
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({
          title,
          description: description.trim() ? description.trim() : null,
          activationCode: reminderKind === "activation" && activationCode.trim() ? activationCode.trim() : null,
          activationContact:
            reminderKind === "activation" && activationContact.trim() ? activationContact.trim() : null,
          dueAt: new Date(dueAt).toISOString(),
          priority,
          category: category.trim() ? category.trim() : null,
          remindBeforeDays: Number(remindBeforeDays),
          remindBeforeHours: Number(remindBeforeHours),
          overdueRemindEnabled,
          recurrenceType: recurrenceType === "none" ? null : recurrenceType,
          recurrenceInterval: recurrenceType === "none" ? null : Number(recurrenceInterval),
        }),
      });

      const data = (await response.json()) as { error?: string };
      if (!response.ok) {
        throw new Error(data.error ?? "保存失败");
      }

      router.push("/reminders");
      router.refresh();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "保存失败");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form className="min-w-0 space-y-4 rounded-xl border border-slate-200 bg-white p-4 sm:p-6" onSubmit={handleSubmit}>
      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">标题</label>
        <Input name="title" placeholder="例如：合同到期前续签" value={title} onChange={(e) => setTitle(e.target.value)} required />
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">截止时间</label>
          <Input name="dueAt" type="datetime-local" value={dueAt} onChange={(e) => setDueAt(e.target.value)} required />
        </div>
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">优先级</label>
          <select className="min-h-11 w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm md:min-h-0" value={priority} onChange={(e) => setPriority(e.target.value as "low" | "medium" | "high") }>
            <option value="high">高</option>
            <option value="medium">中</option>
            <option value="low">低</option>
          </select>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">提前提醒天数</label>
          <Input type="number" min={0} max={30} value={remindBeforeDays} onChange={(e) => setRemindBeforeDays(e.target.value)} />
        </div>
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">提前提醒小时</label>
          <Input type="number" min={0} max={168} value={remindBeforeHours} onChange={(e) => setRemindBeforeHours(e.target.value)} />
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">周期顺延</label>
          <select
            className="min-h-11 w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm md:min-h-0"
            value={recurrenceType}
            onChange={(e) => setRecurrenceType(e.target.value as RecurrenceSelectValue)}
          >
            <option value="none">不重复</option>
            <option value="daily">按天顺延</option>
            <option value="weekly">按周顺延</option>
            <option value="monthly">按月顺延</option>
            <option value="yearly">按年顺延</option>
          </select>
        </div>
        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">周期数值</label>
          <Input
            type="number"
            min={1}
            max={30}
            value={recurrenceInterval}
            onChange={(e) => setRecurrenceInterval(e.target.value)}
            disabled={recurrenceType === "none"}
          />
          <p className="text-xs text-slate-500">完成后，按这里设置的天/周/月/年顺延生成下一期。</p>
        </div>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">提醒分组</label>
        <select
          className="min-h-11 w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm md:min-h-0"
          value={category}
          onChange={(e) => setCategory(e.target.value as ReminderGroup)}
        >
          {REMINDER_GROUPS.map((group) => <option key={group} value={group}>{group}</option>)}
        </select>
        <p className="text-xs text-slate-500">用于提醒列表分区和筛选；旧分类会自动归入对应业务分组。</p>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">说明</label>
        <textarea className="min-h-28 w-full rounded-md border border-slate-200 px-3 py-2 text-sm outline-none" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="补充提醒说明" />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">记录类型</label>
        <select
          className="min-h-11 w-full rounded-md border border-slate-200 bg-white px-3 py-2 text-sm md:min-h-0"
          value={reminderKind}
          onChange={(e) => {
            const nextKind = e.target.value as "normal" | "activation";
            setReminderKind(nextKind);
            if (nextKind === "normal") {
              setActivationCode("");
              setActivationContact("");
            }
          }}
        >
          <option value="normal">普通提醒</option>
          <option value="activation">激活码通知</option>
        </select>
      </div>

      {reminderKind === "activation" ? (
        <div className="space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700">激活码</label>
            <Input value={activationCode} onChange={(e) => setActivationCode(e.target.value)} placeholder="请输入激活码" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700">联系方式</label>
            <Input
              value={activationContact}
              onChange={(e) => setActivationContact(e.target.value)}
              placeholder="例如：微信 / Telegram / 邮箱 / 手机号"
            />
          </div>
          <p className="text-xs text-slate-500">激活码通知会在列表和邮件提醒中单独展示激活码和联系方式。</p>
        </div>
      ) : null}

      <label className="flex min-h-11 items-center gap-2 text-sm text-slate-700 md:min-h-0">
        <input type="checkbox" checked={overdueRemindEnabled} onChange={(e) => setOverdueRemindEnabled(e.target.checked)} />
        超期后继续提醒
      </label>

      <div className="space-y-2">
        <label className="text-sm font-medium text-slate-700">附件</label>
        <FileUpload reminderId={defaultValues?.id} attachments={attachments} />
      </div>

      <div className="flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between sm:gap-4">
        <p className="break-words text-sm text-slate-500">{message ?? ""}</p>
        <Button className="min-h-11 w-full sm:w-auto" type="submit" disabled={submitting}>{submitting ? "保存中..." : mode === "create" ? "创建提醒" : "保存修改"}</Button>
      </div>
    </form>
  );
}

// app/components/reminders/ReminderForm.vue
<script setup lang="ts">
import { safeReturnUrl } from "@/app/composables/useApi";
import { REMINDER_GROUPS, isoToLegacyDateTimeValue, legacyDateTimeValueToIso, reminderGroup, type ReminderItem } from "./reminder";

type Attachment = { id: string; originalName: string; mimetype: string; size: number; url: string; reminderId?: string | null };
const props = defineProps<{ mode: "create" | "edit"; reminder?: ReminderItem; attachments?: Attachment[] }>();
const route = useRoute();
const { apiFetch } = useApi();
const submitting = ref(false);
const kind = ref<"normal" | "activation">(props.reminder?.activationCode ? "activation" : "normal");
const form = reactive({
  title: props.reminder?.title || "",
  description: props.reminder?.description || "",
  activationCode: props.reminder?.activationCode || "",
  activationContact: props.reminder?.activationContact || "",
  // Deliberately identical to legacy datetime-local: UTC ISO is sliced, not converted for display.
  dueAt: props.reminder?.dueAt ? isoToLegacyDateTimeValue(props.reminder.dueAt) : "",
  category: reminderGroup(props.reminder?.category),
  priority: props.reminder?.priority || "medium",
  remindBeforeDays: props.reminder?.remindBeforeDays ?? 3,
  remindBeforeHours: props.reminder?.remindBeforeHours ?? 0,
  overdueRemindEnabled: props.reminder?.overdueRemindEnabled ?? true,
  recurrenceType: props.reminder?.recurrenceType || "none",
  recurrenceInterval: props.reminder?.recurrenceInterval ?? 1,
});

watch(kind, value => { if (value === "normal") { form.activationCode = ""; form.activationContact = ""; } });
async function submit() {
  if (!form.title.trim()) return ElMessage.warning("请输入标题");
  if (!form.dueAt) return ElMessage.warning("请先选择截止时间");
  if (form.recurrenceType !== "none" && form.recurrenceInterval < 1) return ElMessage.warning("周期数值必须大于等于 1");
  if (kind.value === "activation" && form.activationContact.trim() && !form.activationCode.trim()) return ElMessage.warning("请先填写激活码，再补充联系方式");
  submitting.value = true;
  try {
    await apiFetch(props.mode === "create" ? "/api/reminders" : `/api/reminders/${props.reminder!.id}`, {
      method: props.mode === "create" ? "POST" : "PUT",
      body: {
        title: form.title.trim(), description: form.description.trim() || null,
        activationCode: kind.value === "activation" ? form.activationCode.trim() || null : null,
        activationContact: kind.value === "activation" ? form.activationContact.trim() || null : null,
        // Element Plus returns YYYY-MM-DDTHH:mm; Date() preserves legacy browser-timezone serialization.
        dueAt: legacyDateTimeValueToIso(form.dueAt), priority: form.priority, category: form.category,
        remindBeforeDays: Number(form.remindBeforeDays), remindBeforeHours: Number(form.remindBeforeHours),
        overdueRemindEnabled: form.overdueRemindEnabled,
        recurrenceType: form.recurrenceType === "none" ? null : form.recurrenceType,
        recurrenceInterval: form.recurrenceType === "none" ? null : Number(form.recurrenceInterval),
      },
    });
    ElMessage.success(props.mode === "create" ? "提醒已创建" : "提醒已保存");
    await navigateTo(safeReturnUrl(route.query.returnTo, "/reminders"));
  } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); }
  finally { submitting.value = false; }
}
</script>

<template>
  <ElForm class="reminder-form" label-position="top" @submit.prevent="submit">
    <ElFormItem label="标题" required><ElInput v-model="form.title" maxlength="200" show-word-limit placeholder="例如：合同到期前续签" /></ElFormItem>
    <div class="grid two">
      <ElFormItem label="截止时间" required>
        <ElDatePicker v-model="form.dueAt" type="datetime" value-format="YYYY-MM-DDTHH:mm" format="YYYY-MM-DD HH:mm" placeholder="选择截止时间" style="width:100%" />
      </ElFormItem>
      <ElFormItem label="优先级"><ElSelect v-model="form.priority"><ElOption label="高" value="high" /><ElOption label="中" value="medium" /><ElOption label="低" value="low" /></ElSelect></ElFormItem>
    </div>
    <div class="grid two">
      <ElFormItem label="提前提醒天数"><ElInputNumber v-model="form.remindBeforeDays" :min="0" :max="30" /></ElFormItem>
      <ElFormItem label="提前提醒小时"><ElInputNumber v-model="form.remindBeforeHours" :min="0" :max="168" /></ElFormItem>
    </div>
    <div class="grid two">
      <ElFormItem label="周期顺延"><ElSelect v-model="form.recurrenceType"><ElOption label="不重复" value="none" /><ElOption label="按天顺延" value="daily" /><ElOption label="按周顺延" value="weekly" /><ElOption label="按月顺延" value="monthly" /><ElOption label="按年顺延" value="yearly" /></ElSelect></ElFormItem>
      <ElFormItem label="周期数值"><ElInputNumber v-model="form.recurrenceInterval" :min="1" :max="30" :disabled="form.recurrenceType === 'none'" /><small>完成后按设置的天/周/月/年顺延生成下一期。</small></ElFormItem>
    </div>
    <ElFormItem label="提醒分组"><ElSelect v-model="form.category"><ElOption v-for="group in REMINDER_GROUPS" :key="group" :label="group" :value="group" /></ElSelect></ElFormItem>
    <ElFormItem label="说明"><ElInput v-model="form.description" type="textarea" :rows="4" placeholder="补充提醒说明" /></ElFormItem>
    <ElFormItem label="记录类型"><ElSelect v-model="kind"><ElOption label="普通提醒" value="normal" /><ElOption label="激活码通知" value="activation" /></ElSelect></ElFormItem>
    <template v-if="kind === 'activation'">
      <ElFormItem label="激活码"><ElInput v-model="form.activationCode" type="textarea" :rows="4" maxlength="10000" placeholder="请输入激活码" /></ElFormItem>
      <ElFormItem label="联系方式"><ElInput v-model="form.activationContact" maxlength="200" placeholder="例如：微信 / Telegram / 邮箱 / 手机号" /></ElFormItem>
      <p class="hint">激活码仅在编辑记录和通知内容中完整使用，提醒列表不会直接展示。</p>
    </template>
    <ElFormItem><ElCheckbox v-model="form.overdueRemindEnabled">超期后继续提醒</ElCheckbox></ElFormItem>
    <ElFormItem label="附件"><ReminderAttachments :reminder-id="reminder?.id" :initial="attachments" /></ElFormItem>
    <footer><ElButton @click="navigateTo(safeReturnUrl(route.query.returnTo, '/reminders'))">取消</ElButton><ElButton type="primary" native-type="submit" :loading="submitting">{{ mode === 'create' ? '创建提醒' : '保存修改' }}</ElButton></footer>
  </ElForm>
</template>
<style scoped>.reminder-form{padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.grid{display:grid;gap:18px}.two{grid-template-columns:1fr 1fr}.reminder-form :deep(.el-select),.reminder-form :deep(.el-input-number){width:100%}.hint,small{color:#64748b;font-size:12px}.hint{margin:-12px 0 20px}footer{display:flex;justify-content:flex-end;gap:10px;padding-top:18px;border-top:1px solid #e2e8f0}@media(max-width:600px){.two{grid-template-columns:1fr}.reminder-form{padding:14px}}</style>
