// components/todos/todo-list.tsx
"use client";

import { useCallback, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { AlertDialog } from "@/components/ui/alert-dialog";

type TodoItem = {
  id: string;
  title: string;
  completedAt: string | null;
  createdAt: string;
};

export function TodoList({ initialTodos }: { initialTodos: TodoItem[] }) {
  const [todos, setTodos] = useState<TodoItem[]>(initialTodos);
  const [newTitle, setNewTitle] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editTitle, setEditTitle] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const addTodo = useCallback(async () => {
    const title = newTitle.trim();
    if (!title) return;

    const res = await fetch("/api/todos", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title }),
    });
    if (res.ok) {
      const { item } = await res.json();
      setTodos((prev) => [item, ...prev]);
      setNewTitle("");
      inputRef.current?.focus();
    }
  }, [newTitle]);

  const toggleTodo = useCallback(async (id: string, currentCompleted: boolean) => {
    const now = new Date().toISOString();
    setTodos((prev) =>
      prev.map((t) =>
        t.id === id
          ? { ...t, completedAt: currentCompleted ? null : now }
          : t
      )
    );

    await fetch(`/api/todos/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ completed: !currentCompleted }),
    });
  }, []);

  const deleteTodo = useCallback(async (id: string) => {
    setTodos((prev) => prev.filter((t) => t.id !== id));
    await fetch(`/api/todos/${id}`, { method: "DELETE" });
  }, []);

  const startEdit = useCallback((todo: TodoItem) => {
    setEditingId(todo.id);
    setEditTitle(todo.title);
  }, []);

  const saveEdit = useCallback(async (id: string) => {
    const title = editTitle.trim();
    if (!title) return;

    setTodos((prev) =>
      prev.map((t) => (t.id === id ? { ...t, title } : t))
    );
    setEditingId(null);

    await fetch(`/api/todos/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title }),
    });
  }, [editTitle]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "Enter") {
        e.preventDefault();
        if (editingId) {
          saveEdit(editingId);
        } else {
          addTodo();
        }
      }
      if (e.key === "Escape" && editingId) {
        setEditingId(null);
      }
    },
    [addTodo, saveEdit, editingId]
  );

  const pending = todos.filter((t) => !t.completedAt);
  const done = todos.filter((t) => t.completedAt);

  return (
    <div className="mx-auto max-w-2xl">
      <h1 className="mb-5 text-xl font-bold text-balance text-slate-900 sm:mb-6 sm:text-2xl">
        📋 待办事项
      </h1>

      {/* Add input */}
      <div className="mb-6 flex gap-2">
        <input
          ref={inputRef}
          type="text"
          value={newTitle}
          onChange={(e) => setNewTitle(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="添加新的待办事项…"
          className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-900 placeholder:text-slate-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20 sm:px-4"
          autoFocus
        />
        <button
          onClick={addTodo}
          disabled={!newTitle.trim()}
          className="min-h-11 shrink-0 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-40 sm:px-5"
        >
          新增
        </button>
      </div>

      {/* Empty state */}
      {pending.length === 0 && done.length === 0 ? (
        <p className="py-12 text-center text-sm text-pretty text-slate-400">
          暂无待办事项，添加一个吧。
        </p>
      ) : (
        <>
          {/* Pending section */}
          {pending.length > 0 && (
            <div className="mb-8">
              <h2 className="mb-3 text-xs font-semibold uppercase text-slate-400">
                待处理 · {pending.length}
              </h2>
              <ul className="space-y-1.5">
                {pending.map((todo) => (
                  <TodoRow
                    key={todo.id}
                    todo={todo}
                    isEditing={editingId === todo.id}
                    editTitle={editTitle}
                    onEditTitleChange={setEditTitle}
                    onToggle={() => toggleTodo(todo.id, false)}
                    onDelete={() => deleteTodo(todo.id)}
                    onStartEdit={() => startEdit(todo)}
                    onSaveEdit={() => saveEdit(todo.id)}
                    onKeyDown={handleKeyDown}
                  />
                ))}
              </ul>
            </div>
          )}

          {/* Done section */}
          {done.length > 0 && (
            <div>
              <h2 className="mb-3 text-xs font-semibold uppercase text-slate-400">
                已完成 · {done.length}
              </h2>
              <ul className="space-y-1.5">
                {done.map((todo) => (
                  <TodoRow
                    key={todo.id}
                    todo={todo}
                    isEditing={editingId === todo.id}
                    editTitle={editTitle}
                    onEditTitleChange={setEditTitle}
                    onToggle={() => toggleTodo(todo.id, true)}
                    onDelete={() => deleteTodo(todo.id)}
                    onStartEdit={() => startEdit(todo)}
                    onSaveEdit={() => saveEdit(todo.id)}
                    onKeyDown={handleKeyDown}
                  />
                ))}
              </ul>
            </div>
          )}
        </>
      )}
    </div>
  );
}

function TodoRow({
  todo,
  isEditing,
  editTitle,
  onEditTitleChange,
  onToggle,
  onDelete,
  onStartEdit,
  onSaveEdit,
  onKeyDown,
}: {
  todo: TodoItem;
  isEditing: boolean;
  editTitle: string;
  onEditTitleChange: (v: string) => void;
  onToggle: () => void;
  onDelete: () => void;
  onStartEdit: () => void;
  onSaveEdit: () => void;
  onKeyDown: (e: React.KeyboardEvent) => void;
}) {
  const isDone = !!todo.completedAt;

  return (
    <li
      className={cn(
        "group flex min-w-0 items-center gap-2 rounded-lg border px-2 py-2 transition-colors sm:gap-3 sm:px-4 sm:py-2.5",
        isDone
          ? "border-slate-100 bg-slate-50/50"
          : "border-slate-200 bg-white hover:border-slate-300"
      )}
    >
      {/* Checkbox */}
      <button
        onClick={onToggle}
        aria-label={isDone ? "标记待办" : "标记完成"}
        className={cn(
          "flex size-11 shrink-0 items-center justify-center rounded-lg transition-colors",
          isDone
            ? "text-blue-500"
            : "text-slate-300 hover:text-blue-400"
        )}
      >
        <span className={cn("flex size-5 items-center justify-center rounded-full border-2", isDone ? "border-blue-500 bg-blue-500 text-white" : "border-current")}>
          {isDone && (
            <svg className="size-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
            </svg>
          )}
        </span>
      </button>

      {/* Title / Edit */}
      {isEditing ? (
        <input
          type="text"
          value={editTitle}
          onChange={(e) => onEditTitleChange(e.target.value)}
          onKeyDown={onKeyDown}
          className="min-w-0 flex-1 rounded border border-blue-400 bg-white px-2 py-2 text-sm text-slate-900 outline-none ring-2 ring-blue-500/20"
          autoFocus
          onBlur={onSaveEdit}
        />
      ) : (
        <span
          className={cn(
            "min-w-0 flex-1 cursor-pointer break-words text-sm",
            isDone ? "text-slate-400 line-through" : "text-slate-700"
          )}
          onClick={onStartEdit}
        >
          {todo.title}
        </span>
      )}

      {/* Actions — show on hover */}
      {!isEditing && (
        <div className="flex shrink-0 items-center gap-0.5 opacity-100 transition-opacity md:opacity-0 md:group-hover:opacity-100 md:group-focus-within:opacity-100">
          {/* Undo button (only for done items) */}
          {isDone && (
            <button
              onClick={onToggle}
              aria-label="取消完成"
              className="inline-flex size-11 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100 hover:text-amber-500 md:size-9"
            >
              <svg className="size-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
              </svg>
            </button>
          )}
          {/* Delete button — wrapped in AlertDialog */}
          <AlertDialog
            trigger={
              <button
                aria-label="删除"
                className="inline-flex size-11 items-center justify-center rounded-md text-slate-400 hover:bg-red-50 hover:text-red-500 md:size-9"
              >
                <svg className="size-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
              </button>
            }
            title="删除待办事项"
            description={`确定要删除「${todo.title}」吗？此操作不可撤销。`}
            confirmLabel="删除"
            onConfirm={onDelete}
          />
        </div>
      )}

      {/* Completed date */}
      {isDone && todo.completedAt && (
        <span className="hidden shrink-0 text-[11px] text-slate-400 group-hover:hidden sm:inline">
          {new Date(todo.completedAt).toLocaleDateString("zh-CN", { month: "short", day: "numeric" })}
        </span>
      )}
    </li>
  );
}

// app/components/todos/TodoList.vue
<script setup lang="ts">
type TodoItem = {
  id: string;
  title: string;
  completedAt: string | null;
  createdAt: string;
};

const props = defineProps<{ initialTodos: TodoItem[] }>();
const { apiFetch } = useApi();
const todos = ref([...props.initialTodos]);
const newTitle = ref("");
const editingId = ref<string | null>(null);
const editTitle = ref("");
const busyIds = ref(new Set<string>());

const pending = computed(() => todos.value.filter(item => !item.completedAt));
const completed = computed(() => todos.value.filter(item => item.completedAt));

async function addTodo() {
  const title = newTitle.value.trim();
  if (!title) return;
  try {
    const result = await apiFetch<{ item: TodoItem }>("/api/todos", { method: "POST", body: { title } });
    todos.value.unshift(result.item);
    newTitle.value = "";
  } catch (error) {
    ElMessage.error(error instanceof Error ? error.message : "新增失败");
  }
}

async function toggleTodo(todo: TodoItem) {
  if (busyIds.value.has(todo.id)) return;
  busyIds.value.add(todo.id);
  const previous = todo.completedAt;
  todo.completedAt = previous ? null : new Date().toISOString();
  try {
    const result = await apiFetch<{ item: TodoItem }>(`/api/todos/${todo.id}`, {
      method: "PATCH",
      body: { completed: !previous },
    });
    Object.assign(todo, result.item);
  } catch (error) {
    todo.completedAt = previous;
    ElMessage.error(error instanceof Error ? error.message : "更新失败");
  } finally {
    busyIds.value.delete(todo.id);
  }
}

function startEdit(todo: TodoItem) {
  editingId.value = todo.id;
  editTitle.value = todo.title;
}

async function saveEdit(todo: TodoItem) {
  if (editingId.value !== todo.id) return;
  const title = editTitle.value.trim();
  if (!title) {
    ElMessage.warning("标题不能为空");
    return;
  }
  editingId.value = null;
  const previous = todo.title;
  todo.title = title;
  try {
    const result = await apiFetch<{ item: TodoItem }>(`/api/todos/${todo.id}`, { method: "PATCH", body: { title } });
    Object.assign(todo, result.item);
  } catch (error) {
    todo.title = previous;
    ElMessage.error(error instanceof Error ? error.message : "保存失败");
  }
}

async function deleteTodo(todo: TodoItem) {
  try {
    await ElMessageBox.confirm(`确定要删除「${todo.title}」吗？此操作不可撤销。`, "删除待办事项", { type: "warning", confirmButtonText: "删除", cancelButtonText: "取消" });
    await apiFetch(`/api/todos/${todo.id}`, { method: "DELETE" });
    todos.value = todos.value.filter(item => item.id !== todo.id);
  } catch (error) {
    if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "删除失败");
  }
}
</script>

<template>
  <section class="todo-page">
    <h1>📋 待办事项</h1>
    <div class="add-row">
      <ElInput v-model="newTitle" autofocus clearable maxlength="200" placeholder="添加新的待办事项…" aria-label="新待办标题" @keyup.enter="addTodo" />
      <ElButton type="primary" :disabled="!newTitle.trim()" @click="addTodo">新增</ElButton>
    </div>

    <ElEmpty v-if="!todos.length" description="暂无待办事项，添加一个吧。" />
    <template v-else>
      <div v-for="section in [{ label: '待处理', items: pending }, { label: '已完成', items: completed }]" :key="section.label" class="todo-section">
        <template v-if="section.items.length">
          <h2>{{ section.label }} · {{ section.items.length }}</h2>
          <div class="todo-list">
            <div v-for="todo in section.items" :key="todo.id" class="todo-row" :class="{ done: !!todo.completedAt }">
              <ElCheckbox :model-value="!!todo.completedAt" :disabled="busyIds.has(todo.id)" :aria-label="todo.completedAt ? '取消完成' : '标记完成'" @change="toggleTodo(todo)" />
              <ElInput v-if="editingId === todo.id" v-model="editTitle" maxlength="200" aria-label="编辑待办标题" autofocus @keyup.enter="saveEdit(todo)" @keyup.esc="editingId = null" @blur="saveEdit(todo)" />
              <button v-else class="todo-title" type="button" @click="startEdit(todo)">{{ todo.title }}</button>
              <span v-if="todo.completedAt" class="completed-date">{{ new Date(todo.completedAt).toLocaleDateString('zh-CN') }}</span>
              <ElButton text aria-label="编辑" @click="startEdit(todo)">编辑</ElButton>
              <ElButton text type="danger" aria-label="删除" @click="deleteTodo(todo)">删除</ElButton>
            </div>
          </div>
        </template>
      </div>
    </template>
  </section>
</template>

<style scoped>
.todo-page{max-width:760px;margin:auto}.todo-page h1{margin:0 0 24px;font-size:24px}.add-row{display:flex;gap:10px;margin-bottom:28px}.todo-section{margin-top:24px}.todo-section h2{color:#64748b;font-size:13px;text-transform:uppercase}.todo-list{display:grid;gap:8px}.todo-row{display:flex;align-items:center;gap:10px;min-width:0;padding:10px 14px;border:1px solid #e2e8f0;border-radius:10px;background:#fff}.todo-row.done{background:#f8fafc}.todo-title{flex:1;min-width:0;padding:6px 0;border:0;background:none;text-align:left;color:#334155;cursor:pointer;overflow-wrap:anywhere}.done .todo-title{text-decoration:line-through;color:#94a3b8}.completed-date{font-size:11px;color:#94a3b8}@media(max-width:600px){.completed-date{display:none}.todo-row{padding:8px}.todo-row :deep(.el-button){padding:6px}}
</style>
